/*
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ParticipantObject1;
import java.util.ArrayList;
import java.util.List;

/**
 * CallSessionInformation1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-12T11:22:21.454Z")
public class CallSessionInformation1 {
  @SerializedName("participant")
  private List<ParticipantObject1> participant = new ArrayList<ParticipantObject1>();

  public CallSessionInformation1 participant(List<ParticipantObject1> participant) {
    this.participant = participant;
    return this;
  }

  public CallSessionInformation1 addParticipantItem(ParticipantObject1 participantItem) {
    this.participant.add(participantItem);
    return this;
  }

   /**
   * Get participant
   * @return participant
  **/
  @ApiModelProperty(example = "[{&quot;participantAddress&quot;:&quot;sip:+358987654321@ims8.wirelessfuture.com&quot;},{&quot;participantAddress&quot;:&quot;sip:+358123456789@ims8.wirelessfuture.com&quot;}]", required = true, value = "")
  public List<ParticipantObject1> getParticipant() {
    return participant;
  }

  public void setParticipant(List<ParticipantObject1> participant) {
    this.participant = participant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallSessionInformation1 callSessionInformation1 = (CallSessionInformation1) o;
    return Objects.equals(this.participant, callSessionInformation1.participant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(participant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallSessionInformation1 {\n");
    
    sb.append("    participant: ").append(toIndentedString(participant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

