/*
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CallEventFilter1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-12T11:22:21.454Z")
public class CallEventFilter1 {
  @SerializedName("address")
  private List<String> address = new ArrayList<String>();

  /**
   * Gets or Sets criteria
   */
  public enum CriteriaEnum {
    @SerializedName("Answer")
    ANSWER("Answer"),
    
    @SerializedName("Busy")
    BUSY("Busy"),
    
    @SerializedName("CalledNumber")
    CALLEDNUMBER("CalledNumber"),
    
    @SerializedName("Disconnected")
    DISCONNECTED("Disconnected"),
    
    @SerializedName("NoAnswer")
    NOANSWER("NoAnswer"),
    
    @SerializedName("NotReachable")
    NOTREACHABLE("NotReachable");

    private String value;

    CriteriaEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("criteria")
  private List<CriteriaEnum> criteria = new ArrayList<CriteriaEnum>();

  /**
   * Gets or Sets addressDirection
   */
  public enum AddressDirectionEnum {
    @SerializedName("Called")
    CALLED("Called"),
    
    @SerializedName("Calling")
    CALLING("Calling");

    private String value;

    AddressDirectionEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("addressDirection")
  private AddressDirectionEnum addressDirection = null;

  public CallEventFilter1 address(List<String> address) {
    this.address = address;
    return this;
  }

  public CallEventFilter1 addAddressItem(String addressItem) {
    this.address.add(addressItem);
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(example = "[&quot;sip:+358123456789@ims8.wirelessfuture.com&quot;]", required = true, value = "")
  public List<String> getAddress() {
    return address;
  }

  public void setAddress(List<String> address) {
    this.address = address;
  }

  public CallEventFilter1 criteria(List<CriteriaEnum> criteria) {
    this.criteria = criteria;
    return this;
  }

  public CallEventFilter1 addCriteriaItem(CriteriaEnum criteriaItem) {
    this.criteria.add(criteriaItem);
    return this;
  }

   /**
   * Get criteria
   * @return criteria
  **/
  @ApiModelProperty(example = "[&quot;CalledNumber&quot;]", value = "")
  public List<CriteriaEnum> getCriteria() {
    return criteria;
  }

  public void setCriteria(List<CriteriaEnum> criteria) {
    this.criteria = criteria;
  }

  public CallEventFilter1 addressDirection(AddressDirectionEnum addressDirection) {
    this.addressDirection = addressDirection;
    return this;
  }

   /**
   * Get addressDirection
   * @return addressDirection
  **/
  @ApiModelProperty(example = "Called", value = "")
  public AddressDirectionEnum getAddressDirection() {
    return addressDirection;
  }

  public void setAddressDirection(AddressDirectionEnum addressDirection) {
    this.addressDirection = addressDirection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallEventFilter1 callEventFilter1 = (CallEventFilter1) o;
    return Objects.equals(this.address, callEventFilter1.address) &&
        Objects.equals(this.criteria, callEventFilter1.criteria) &&
        Objects.equals(this.addressDirection, callEventFilter1.addressDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, criteria, addressDirection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallEventFilter1 {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("    addressDirection: ").append(toIndentedString(addressDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

