/*
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ClickToCallResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-12T11:22:21.454Z")
public class ClickToCallResponse {
  @SerializedName("caller")
  private String caller = null;

  @SerializedName("callee")
  private String callee = null;

  public ClickToCallResponse caller(String caller) {
    this.caller = caller;
    return this;
  }

   /**
   * Get caller
   * @return caller
  **/
  @ApiModelProperty(example = "sip:+358987654321@ims8.wirelessfuture.com", required = true, value = "")
  public String getCaller() {
    return caller;
  }

  public void setCaller(String caller) {
    this.caller = caller;
  }

  public ClickToCallResponse callee(String callee) {
    this.callee = callee;
    return this;
  }

   /**
   * Get callee
   * @return callee
  **/
  @ApiModelProperty(example = "sip:+358123456789@ims8.wirelessfuture.com", required = true, value = "")
  public String getCallee() {
    return callee;
  }

  public void setCallee(String callee) {
    this.callee = callee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClickToCallResponse clickToCallResponse = (ClickToCallResponse) o;
    return Objects.equals(this.caller, clickToCallResponse.caller) &&
        Objects.equals(this.callee, clickToCallResponse.callee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caller, callee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClickToCallResponse {\n");
    
    sb.append("    caller: ").append(toIndentedString(caller)).append("\n");
    sb.append("    callee: ").append(toIndentedString(callee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

