/*
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CallDirectionSubscriptionResponse1;
import io.swagger.client.model.CallDirectionSubscriptionWrapper1;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionApi
 */
@Ignore
public class SubscriptionApiTest {

    private final SubscriptionApi api = new SubscriptionApi();

    
    /**
     * Create a call direction subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSubscriptionTest() throws ApiException {
        CallDirectionSubscriptionWrapper1 callDirectionSubscription = null;
        CallDirectionSubscriptionResponse1 response = api.createSubscription(callDirectionSubscription);

        // TODO: test validations
    }
    
    /**
     * Delete a call direction subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSubscriptionTest() throws ApiException {
        String id = null;
        String addr = null;
        api.deleteSubscription(id, addr);

        // TODO: test validations
    }
    
    /**
     * Read a call direction subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubscriptionTest() throws ApiException {
        String id = null;
        String addr = null;
        CallDirectionSubscriptionResponse1 response = api.getSubscription(id, addr);

        // TODO: test validations
    }
    
}
